CREATE TABLE IF NOT EXISTS USERS (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ROLES (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS USER_ROLES (
    USER_ID UUID,
    ROLE_ID UUID,
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE
);


-- -- Sample data insertion (optional)
INSERT INTO ROLES (ID, NAME) VALUES (RANDOM_UUID(), 'ROLE_USER');
INSERT INTO ROLES (ID, NAME) VALUES (RANDOM_UUID(), 'ROLE_ADMIN');

-- INSERT INTO USERS (ID, USERNAME, PASSWORD) VALUES (RANDOM_UUID(), 'user1', 'password1');
-- INSERT INTO USERS (ID, USERNAME, PASSWORD) VALUES (RANDOM_UUID(), 'admin', 'adminpass');

-- INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
-- SELECT u.ID, r.ID FROM USERS u, ROLES r WHERE u.USERNAME = 'user1' AND r.NAME = 'ROLE_USER';

-- INSERT INTO USER_ROLES (USER_ID, ROLE_ID)
-- SELECT u.ID, r.ID FROM USERS u, ROLES r WHERE u.USERNAME = 'admin' AND r.NAME = 'ROLE_ADMIN';
